### ISSUE TITLE
Upscale

### ISSUE THREAD

**Issue by ufleming** [seamus-oconnor/gulp-jimp#12]
How can I set "upscale" to false?

**Comment by seamus-oconnor** [comment]
I checked the jimp documentation and I found no mention of 'upscale' as a parameter that you can set to false. Are you asking how to resize but prevent upscaling? This lib passes the config params to jimp so you might want to check there to see how to resize w/o upscaling.

**Comment by ufleming** [comment]
Yes I want to prevent upscaling.
I want to generate thumbnails for big images and just copy small without resize.

**Comment by seamus-oconnor** [comment]
My guess is that you would have to read the size of the image before you resized it. There is nothing in this library to do that for you. Best to read the [JIMP](https://github.com/oliver-moran/jimp) documentation.
